version: '3'
services:

#  instances for US cluster
  bk-us:
    hostname: bk-us
    container_name: bk-us
    image: apachepulsar/pulsar:2.4.1
    expose: [8000]
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/bookkeeper.conf
      && bin/pulsar bookie"
    environment:
      clusterName: cluster-us
      zkServers: zk-us:2181
#      advertisedAddress: bk-us:3181
#      numAddWorkerThreads: 8
#      useHostNameAsBookieID: "true"
    networks:
      - datacenter-network

  broker-us:
    hostname: broker-us
    container_name: broker-us
    image: apachepulsar/pulsar:2.4.1
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/broker.conf
      && bin/pulsar broker"
    expose: [8080, 6650]
    environment:
      clusterName: cluster-us
      zookeeperServers: zk-us:2181
      configurationStoreServers: zk-us:2181
      managedLedgerDefaultEnsembleSize: 1
      managedLedgerDefaultWriteQuorum: 1
      managedLedgerDefaultAckQuorum: 1
      bookkeeperClientRegionawarePolicyEnabled: "true"
#      bookkeeperClientReorderReadSequenceEnabled: "true"
#      webSocketServiceEnabled: "true"
    networks:
      - datacenter-network

networks:
  datacenter-network:
    external: true
