version: '3'
services:

#  instances for US cluster
  zk-us:
    hostname: zk-us
    container_name: zk-us
    image: apachepulsar/pulsar:2.4.1
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/zookeeper.conf
      && bin/pulsar zookeeper"
    environment:
      ZOOKEEPER_SERVERS: zk-us
    ports:
      - "2181"
      - "8000"
    networks:
      - datacenter-network

networks:
  datacenter-network:
    external: true
