version: '3'
services:

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 10 --cleanup pulsar-producer pulsar-consumer
    networks:
      - docker-network

  zk:
    image: zookeeper:3.4.14
    container_name: zk
    hostname: zk
    ports:
      - "2181:2181"
    networks:
      - docker-network

  pulsar:
    image: apachepulsar/pulsar
    container_name: pulsar
    hostname: pulsar
#    volumes:
#      - ${PWD}/data:/pulsar/data
    environment:
      ZK_HOST: zk:2181
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"
    depends_on:
      - zk
    ports:
      - "6650:6650"
      - "8080:8080"
    restart: always
    networks:
      - docker-network

  pulsar-dashboard:
    image: apachepulsar/pulsar-dashboard
    container_name: pulsar-dashboard
    depends_on:
      - pulsar
    ports:
      - "80:80"
    environment:
      SERVICE_URL: http://pulsar:8080
    networks:
      - docker-network

  pulsar-producer:
    image: 127.0.0.1:5000/pulsar-producer
    container_name: pulsar-producer
    ports:
      - "8081:8081"
    depends_on:
      - pulsar
    networks:
      - docker-network

  pulsar-consumer:
    image: 127.0.0.1:5000/pulsar-consumer
    container_name: pulsar-consumer
    ports:
      - "8082:8082"
    depends_on:
      - pulsar
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
