version: '3'
services:

  pulsar-proxy:
    hostname: pulsar-proxy
    container_name: pulsar-proxy
    image: apachepulsar/pulsar:2.4.1
    expose: [8000]
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/proxy.conf
      && bin/pulsar proxy"
    environment:
      zookeeperServers: zk:2181
      configurationStoreServers: zk:2181
    networks:
      - datacenter-network

networks:
  datacenter-network:
    external: true
