version: '3'
services:

  bk:
    hostname: bk
    container_name: bk
    image: apachepulsar/pulsar:2.4.1
    expose: [8000]
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/bookkeeper.conf
      && bin/pulsar bookie"
    environment:
      clusterName: demo-cluster
      zkServers: zk:2181
    #      advertisedAddress: bk-eu:3181
    #      numAddWorkerThreads: 8
    #      useHostNameAsBookieID: "true"
    networks:
      - datacenter-network

  broker:
    hostname: broker
    container_name: broker
    image: apachepulsar/pulsar:2.4.1
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/broker.conf
      && bin/pulsar broker"
    expose: [8080, 6650]
    environment:
      clusterName: demo-cluster
      zookeeperServers: zk:2181
      configurationStoreServers: zk:2181
      managedLedgerDefaultEnsembleSize: 1     # set to match the number of bookeepers in the cluster
      managedLedgerDefaultWriteQuorum: 1      # set to match the number of bookeepers in the cluster
      managedLedgerDefaultAckQuorum: 1        # set to match the number of bookeepers in the cluster
      bookkeeperClientRegionawarePolicyEnabled: "true"
    #      bookkeeperClientReorderReadSequenceEnabled: "true"
    #      webSocketServiceEnabled: "true"
    networks:
      - datacenter-network

networks:
  datacenter-network:
    external: true
